// app/layout.tsx
export const metadata = {
  title: "Sumbo Web",
  description: "Generated by ChatGPT",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
